### PR TITLE
PL - happy birthday card trinket

### PR DESCRIPTION
**Pull request by codecleaner**

### CODE REVIEW

**Comment by martinpeck** [comment]
@codecleaner: It would be useful to know if this, and the previous pull requests, are one-offs or likely to be a common thing.

Is the idea here that you simply add `-pl` to the end of a jumpto.cc link and you get the Polish version of a given resource? If so, I can't see this scaling very well as we introduce other languages. 

I'd also like to better understand the scenario. 

What situation is the user in where they are looking at a jumpto.cc link and adding `-pl` to the end? Are they reading printed material (presumably, in English) or is this while using an online resource? 

Because jumpto.cc short urls never sit around in the browser (because they instantly redirect elsewhere) I have to assume that the only way the user can add `-pl` to the end is by reading the short url, typing it in, and then adding the `-pl`.

Either way, fixing this in the jumpto.cc short url config doesn't feel like the right thing to do either...
1. The source material should have been aware that the user wanted to read non-English, or already have been translated
2. The destination should be language aware and either automatically show, or give as an option, the non-English version

@CodeClubRik I'm happy for you to merge this one in the mean time if it helps @codecleaner out.

**Comment by rikcross** [comment]
@martinpeck I think in this case, the jumpto link is needed for a translation of this page:

http://projects.codeclub.org.uk/en-GB/05_html_01/01/Happy%20Birthday.html

This page does include jumpto links, as a quick way to access trinkets via the pdf versions of the projects.

screen shot 2015-08-26 at 09 00 53

I agree that this won't scale very well, but I don't know of a better way to do this.

**Comment by martinpeck** [comment]
Sure, but the scenario here is that someone is reading and entirely English project and then opening a Polish trinket, right? 

It would be better to have them read a Polish project that already has a polish link e.g. it would have something like...

`jumpto.cc/kartka-internetowa`

(sorry if that's not a good translation @codecleaner)

As I say...it's not the end of the world, but I'd like to make sure we capture what's happening here so that we can either make plinky better, or avoid this problem in the first place.

**Comment by rikcross** [comment]
> Sure, but the scenario here is that someone is reading and entirely English project and then opening a Polish trinket, right?

I am making the assumption that a Polish version of the project notes will follow, and include a link to a Polish Trinket. If this is the case, then I agree that a link like `jumpto.cc/kartka-internetowa` would be better.

**Comment by codecleaner** [comment]
@CodeClubRik you're right - I'm preparing polish translation of Happy Birthday project and those trinkets are needed to make it complete. I also agree that jumpto.cc/kartka-urodzinowa is better.

I will prepare new pull request that will change polish links.

**Comment by codecleaner** [comment]
Is it possible to keep links in separate YAML files? I mean one generic file with generic or international links and separate files for each country. Maybe it could help manage it...

@CodeClubRik @martinpeck What do you think?

**Comment by martinpeck** [comment]
Plinky doesn't support multi files, and it's designed (by me) to be as stupid as possible. I also think there are better ways to cope with that management problem.

I'll have a think about how this might work. For now, I suggest doing what you're doing.

**Comment by codecleaner** [comment]
I mean it could read links from all the files in given directory instead of one given file. Is it too smart for "as stupid as possible" app? :) I'll leave it to you.

**Comment by rikcross** [comment]
Thanks @codecleaner I've merged those too!

**Pull request merged**
