### PR TITLE
Tell a Story - PL shortcuts

### PR DESCRIPTION
**Pull request by codecleaner**

### CODE REVIEW

**Comment by martinpeck** [comment]
@codecleaner Thanks!

I'm going to merge all of this file into the original `cc_shortcuts.yaml`, so can you hold off many any further changes for a short while?

**Comment by codecleaner** [comment]
@martinpeck Sure!

**Comment by martinpeck** [comment]
I've now...
1. deleted the `cc-shortcuts-new.yaml`
2. copied everything over to the `cc-shortcuts.yaml`, including your most recent changes
3. deployed everything

... so, hopefully, your links should still be there, working, and the file to update in future is `cc-shortcuts.yaml`.

**Comment by codecleaner** [comment]
Thanks, everything works fine now!

**Pull request merged**
