### PR TITLE
Fix some 404ing URLs

### PR DESCRIPTION
**Pull request by andylolz**

### CODE REVIEW

**Comment by martinpeck** [comment]
@CodeClubRik these are your babies, but I assume that @andylolz has made valid updates. Please review post merge.

**Comment by rikcross** [comment]
Thanks @andylolz - changes look good.

**Comment by andylolz** [comment]
There are various daisy-chained redirects in there, too (mostly related to https, but also a change to the trinket URL structure). I can send a PR for those too if you’re interested?

**Comment by rikcross** [comment]
yes please!

**Comment by martinpeck** [comment]
The urls in that .yaml file are based upon the export of everything in bit.ly, so if we had "messed up stuff" in bit.ly then we'll certainly have "messed up stuff" here also. 

Have at it, but I would suggest you don't break any back compat (i.e. don't break a url that might be out there in the wild and being used). We have stats being generated on all of these short urls, so after a month we can get a better picture of what's being used (and what can be killed off).

**Pull request merged**
